[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (build output)
  publish = "dist"
  
  # Base directory for build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "9"

# Redirects and rewrites for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers for API calls
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API proxy for Supabase functions
[[redirects]]
  from = "/api/*"
  to = "https://gjvtncdjcslnkfctqnfy.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Proxy for Overleaf integration
[[redirects]]
  from = "/overleaf/*"
  to = "https://www.overleaf.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Form handling (if needed for contact forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Environment variables (these will be set in Netlify UI)
[context.production.environment]
  NODE_ENV = "production"
  VITE_APP_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  VITE_APP_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  VITE_APP_ENV = "branch"

# Functions configuration for Netlify Functions (if using)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Edge functions configuration
[edge_functions]
  directory = "netlify/edge-functions"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Development settings
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  autoLaunch = false

# Build optimization
[build.processing.images]
  compress = true 